# Generated by Django 5.1.1 on 2024-10-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likess',
            field=models.ManyToManyField(blank=True, related_name='likes', to='network.like'),
        ),
    ]
