# Generated by Django 5.1.1 on 2024-10-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_post_likes_post_likess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likess',
            new_name='likes',
        ),
    ]
