# Generated by Django 5.1.1 on 2024-10-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_likess_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
