# Generated by Django 5.1.1 on 2024-10-11 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_follower_delete_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='user',
        ),
        migrations.AddField(
            model_name='follower',
            name='follower_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follower_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follower',
            name='following',
            field=models.ManyToManyField(blank=True, default=[0], related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
