# Generated by Django 5.1.1 on 2024-10-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_follower_follower_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
